// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AuditLogsColumns holds the columns for the "audit_logs" table.
	AuditLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Size: 15},
		{Name: "createdAt", Type: field.TypeTime},
		{Name: "updatedAt", Type: field.TypeTime},
		{Name: "created_by", Type: field.TypeUUID, Nullable: true},
		{Name: "updated_by", Type: field.TypeUUID, Nullable: true},
		{Name: "action", Type: field.TypeString},
		{Name: "object_type", Type: field.TypeString, Nullable: true},
		{Name: "object_id", Type: field.TypeString, Nullable: true},
		{Name: "actor", Type: field.TypeUUID, Nullable: true},
		{Name: "data", Type: field.TypeJSON, Nullable: true},
	}
	// AuditLogsTable holds the schema information for the "audit_logs" table.
	AuditLogsTable = &schema.Table{
		Name:       "audit_logs",
		Columns:    AuditLogsColumns,
		PrimaryKey: []*schema.Column{AuditLogsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "auditlog_object_type_object_id",
				Unique:  false,
				Columns: []*schema.Column{AuditLogsColumns[6], AuditLogsColumns[7]},
			},
			{
				Name:    "auditlog_actor",
				Unique:  false,
				Columns: []*schema.Column{AuditLogsColumns[8]},
			},
		},
	}
	// CamerasColumns holds the columns for the "cameras" table.
	CamerasColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Size: 15},
		{Name: "createdAt", Type: field.TypeTime},
		{Name: "updatedAt", Type: field.TypeTime},
		{Name: "created_by", Type: field.TypeUUID, Nullable: true},
		{Name: "updated_by", Type: field.TypeUUID, Nullable: true},
		{Name: "name", Type: field.TypeString},
		{Name: "user_id", Type: field.TypeUUID},
	}
	// CamerasTable holds the schema information for the "cameras" table.
	CamerasTable = &schema.Table{
		Name:       "cameras",
		Columns:    CamerasColumns,
		PrimaryKey: []*schema.Column{CamerasColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "cameras_users_cameras",
				Columns:    []*schema.Column{CamerasColumns[6]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "camera_user_id",
				Unique:  false,
				Columns: []*schema.Column{CamerasColumns[6]},
			},
			{
				Name:    "camera_name_user_id",
				Unique:  true,
				Columns: []*schema.Column{CamerasColumns[5], CamerasColumns[6]},
			},
		},
	}
	// ImagesColumns holds the columns for the "images" table.
	ImagesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Size: 15},
		{Name: "createdAt", Type: field.TypeTime},
		{Name: "updatedAt", Type: field.TypeTime},
		{Name: "created_by", Type: field.TypeUUID, Nullable: true},
		{Name: "updated_by", Type: field.TypeUUID, Nullable: true},
		{Name: "file_name", Type: field.TypeString},
		{Name: "computed_file_name", Type: field.TypeString, Unique: true, Nullable: true},
		{Name: "storage_id", Type: field.TypeString, Unique: true},
		{Name: "exif_data", Type: field.TypeJSON, Nullable: true},
		{Name: "image_tags", Type: field.TypeJSON, Nullable: true},
		{Name: "captured_at", Type: field.TypeTime, Nullable: true},
		{Name: "captured_at_corrected", Type: field.TypeTime, Nullable: true},
		{Name: "inferred_at", Type: field.TypeTime, Nullable: true},
		{Name: "size", Type: field.TypeInt},
		{Name: "width", Type: field.TypeInt, Nullable: true},
		{Name: "height", Type: field.TypeInt, Nullable: true},
		{Name: "camera_id", Type: field.TypeString, Size: 15},
		{Name: "project_id", Type: field.TypeString, Size: 15},
		{Name: "upload_id", Type: field.TypeString, Size: 15},
		{Name: "user_id", Type: field.TypeUUID},
	}
	// ImagesTable holds the schema information for the "images" table.
	ImagesTable = &schema.Table{
		Name:       "images",
		Columns:    ImagesColumns,
		PrimaryKey: []*schema.Column{ImagesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "images_cameras_images",
				Columns:    []*schema.Column{ImagesColumns[16]},
				RefColumns: []*schema.Column{CamerasColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "images_projects_images",
				Columns:    []*schema.Column{ImagesColumns[17]},
				RefColumns: []*schema.Column{ProjectsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "images_uploads_images",
				Columns:    []*schema.Column{ImagesColumns[18]},
				RefColumns: []*schema.Column{UploadsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "images_users_images",
				Columns:    []*schema.Column{ImagesColumns[19]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "image_project_id",
				Unique:  false,
				Columns: []*schema.Column{ImagesColumns[17]},
			},
			{
				Name:    "image_upload_id",
				Unique:  false,
				Columns: []*schema.Column{ImagesColumns[18]},
			},
			{
				Name:    "image_user_id",
				Unique:  false,
				Columns: []*schema.Column{ImagesColumns[19]},
			},
			{
				Name:    "image_camera_id",
				Unique:  false,
				Columns: []*schema.Column{ImagesColumns[16]},
			},
			{
				Name:    "image_captured_at_corrected",
				Unique:  false,
				Columns: []*schema.Column{ImagesColumns[11]},
			},
			{
				Name:    "image_project_id_captured_at_corrected",
				Unique:  false,
				Columns: []*schema.Column{ImagesColumns[17], ImagesColumns[11]},
			},
			{
				Name:    "image_image_tags",
				Unique:  false,
				Columns: []*schema.Column{ImagesColumns[9]},
				Annotation: &entsql.IndexAnnotation{
					OpClass: "jsonb_path_ops",
					Type:    "GIN",
				},
			},
		},
	}
	// ImageTagsColumns holds the columns for the "image_tags" table.
	ImageTagsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Size: 15},
		{Name: "createdAt", Type: field.TypeTime},
		{Name: "updatedAt", Type: field.TypeTime},
		{Name: "created_by", Type: field.TypeUUID, Nullable: true},
		{Name: "updated_by", Type: field.TypeUUID, Nullable: true},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString},
		{Name: "is_album", Type: field.TypeBool, Default: false},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"template", "default", "manual", "custom"}},
		{Name: "project_id", Type: field.TypeString, Size: 15},
	}
	// ImageTagsTable holds the schema information for the "image_tags" table.
	ImageTagsTable = &schema.Table{
		Name:       "image_tags",
		Columns:    ImageTagsColumns,
		PrimaryKey: []*schema.Column{ImageTagsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "image_tags_projects_imageTags",
				Columns:    []*schema.Column{ImageTagsColumns[9]},
				RefColumns: []*schema.Column{ProjectsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "imagetag_project_id",
				Unique:  false,
				Columns: []*schema.Column{ImageTagsColumns[9]},
			},
			{
				Name:    "imagetag_name_project_id",
				Unique:  true,
				Columns: []*schema.Column{ImageTagsColumns[5], ImageTagsColumns[9]},
			},
		},
	}
	// ImageTagAssignmentsColumns holds the columns for the "image_tag_assignments" table.
	ImageTagAssignmentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Size: 15},
		{Name: "createdAt", Type: field.TypeTime},
		{Name: "updatedAt", Type: field.TypeTime},
		{Name: "created_by", Type: field.TypeUUID, Nullable: true},
		{Name: "updated_by", Type: field.TypeUUID, Nullable: true},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"manual", "inferred", "default"}},
		{Name: "image_id", Type: field.TypeString, Size: 15},
		{Name: "image_tag_id", Type: field.TypeString, Size: 15},
	}
	// ImageTagAssignmentsTable holds the schema information for the "image_tag_assignments" table.
	ImageTagAssignmentsTable = &schema.Table{
		Name:       "image_tag_assignments",
		Columns:    ImageTagAssignmentsColumns,
		PrimaryKey: []*schema.Column{ImageTagAssignmentsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "image_tag_assignments_images_imageTagAssignments",
				Columns:    []*schema.Column{ImageTagAssignmentsColumns[6]},
				RefColumns: []*schema.Column{ImagesColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "image_tag_assignments_image_tags_tagAssignments",
				Columns:    []*schema.Column{ImageTagAssignmentsColumns[7]},
				RefColumns: []*schema.Column{ImageTagsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "imagetagassignment_image_id_image_tag_id",
				Unique:  true,
				Columns: []*schema.Column{ImageTagAssignmentsColumns[6], ImageTagAssignmentsColumns[7]},
			},
			{
				Name:    "imagetagassignment_image_id",
				Unique:  false,
				Columns: []*schema.Column{ImageTagAssignmentsColumns[6]},
			},
			{
				Name:    "imagetagassignment_image_tag_id",
				Unique:  false,
				Columns: []*schema.Column{ImageTagAssignmentsColumns[7]},
			},
		},
	}
	// ProjectsColumns holds the columns for the "projects" table.
	ProjectsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Size: 15},
		{Name: "createdAt", Type: field.TypeTime},
		{Name: "updatedAt", Type: field.TypeTime},
		{Name: "created_by", Type: field.TypeUUID, Nullable: true},
		{Name: "updated_by", Type: field.TypeUUID, Nullable: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "description", Type: field.TypeString},
		{Name: "copyright", Type: field.TypeString},
		{Name: "copyright_reference", Type: field.TypeString},
		{Name: "location_name", Type: field.TypeString},
		{Name: "location_code", Type: field.TypeString},
		{Name: "location_city", Type: field.TypeString},
		{Name: "ai_system_message", Type: field.TypeString, Nullable: true},
	}
	// ProjectsTable holds the schema information for the "projects" table.
	ProjectsTable = &schema.Table{
		Name:       "projects",
		Columns:    ProjectsColumns,
		PrimaryKey: []*schema.Column{ProjectsColumns[0]},
	}
	// ProjectAssignmentsColumns holds the columns for the "project_assignments" table.
	ProjectAssignmentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Size: 15},
		{Name: "createdAt", Type: field.TypeTime},
		{Name: "updatedAt", Type: field.TypeTime},
		{Name: "created_by", Type: field.TypeUUID, Nullable: true},
		{Name: "updated_by", Type: field.TypeUUID, Nullable: true},
		{Name: "project_id", Type: field.TypeString, Size: 15},
		{Name: "role_id", Type: field.TypeString, Size: 15},
		{Name: "user_id", Type: field.TypeUUID},
	}
	// ProjectAssignmentsTable holds the schema information for the "project_assignments" table.
	ProjectAssignmentsTable = &schema.Table{
		Name:       "project_assignments",
		Columns:    ProjectAssignmentsColumns,
		PrimaryKey: []*schema.Column{ProjectAssignmentsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "project_assignments_projects_projectAssignments",
				Columns:    []*schema.Column{ProjectAssignmentsColumns[5]},
				RefColumns: []*schema.Column{ProjectsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "project_assignments_roles_projectAssignments",
				Columns:    []*schema.Column{ProjectAssignmentsColumns[6]},
				RefColumns: []*schema.Column{RolesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "project_assignments_users_projectAssignments",
				Columns:    []*schema.Column{ProjectAssignmentsColumns[7]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "projectassignment_project_id_user_id",
				Unique:  true,
				Columns: []*schema.Column{ProjectAssignmentsColumns[5], ProjectAssignmentsColumns[7]},
			},
			{
				Name:    "projectassignment_user_id",
				Unique:  false,
				Columns: []*schema.Column{ProjectAssignmentsColumns[7]},
			},
			{
				Name:    "projectassignment_role_id",
				Unique:  false,
				Columns: []*schema.Column{ProjectAssignmentsColumns[6]},
			},
		},
	}
	// RolesColumns holds the columns for the "roles" table.
	RolesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Size: 15},
		{Name: "createdAt", Type: field.TypeTime},
		{Name: "updatedAt", Type: field.TypeTime},
		{Name: "created_by", Type: field.TypeUUID, Nullable: true},
		{Name: "updated_by", Type: field.TypeUUID, Nullable: true},
		{Name: "key", Type: field.TypeString, Unique: true},
		{Name: "description", Type: field.TypeString},
	}
	// RolesTable holds the schema information for the "roles" table.
	RolesTable = &schema.Table{
		Name:       "roles",
		Columns:    RolesColumns,
		PrimaryKey: []*schema.Column{RolesColumns[0]},
	}
	// TimeOffsetsColumns holds the columns for the "time_offsets" table.
	TimeOffsetsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Size: 15},
		{Name: "createdAt", Type: field.TypeTime},
		{Name: "updatedAt", Type: field.TypeTime},
		{Name: "created_by", Type: field.TypeUUID, Nullable: true},
		{Name: "updated_by", Type: field.TypeUUID, Nullable: true},
		{Name: "server_time", Type: field.TypeTime},
		{Name: "camera_time", Type: field.TypeTime},
		{Name: "time_offset", Type: field.TypeInt, Nullable: true},
		{Name: "camera_id", Type: field.TypeString, Size: 15},
	}
	// TimeOffsetsTable holds the schema information for the "time_offsets" table.
	TimeOffsetsTable = &schema.Table{
		Name:       "time_offsets",
		Columns:    TimeOffsetsColumns,
		PrimaryKey: []*schema.Column{TimeOffsetsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "time_offsets_cameras_timeOffsets",
				Columns:    []*schema.Column{TimeOffsetsColumns[8]},
				RefColumns: []*schema.Column{CamerasColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "timeoffset_camera_id",
				Unique:  false,
				Columns: []*schema.Column{TimeOffsetsColumns[8]},
			},
		},
	}
	// UploadsColumns holds the columns for the "uploads" table.
	UploadsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Size: 15},
		{Name: "createdAt", Type: field.TypeTime},
		{Name: "updatedAt", Type: field.TypeTime},
		{Name: "created_by", Type: field.TypeUUID, Nullable: true},
		{Name: "updated_by", Type: field.TypeUUID, Nullable: true},
		{Name: "name", Type: field.TypeString},
		{Name: "camera_id", Type: field.TypeString, Size: 15},
		{Name: "project_id", Type: field.TypeString, Size: 15},
		{Name: "user_id", Type: field.TypeUUID},
	}
	// UploadsTable holds the schema information for the "uploads" table.
	UploadsTable = &schema.Table{
		Name:       "uploads",
		Columns:    UploadsColumns,
		PrimaryKey: []*schema.Column{UploadsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "uploads_cameras_uploads",
				Columns:    []*schema.Column{UploadsColumns[6]},
				RefColumns: []*schema.Column{CamerasColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "uploads_projects_uploads",
				Columns:    []*schema.Column{UploadsColumns[7]},
				RefColumns: []*schema.Column{ProjectsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "uploads_users_uploads",
				Columns:    []*schema.Column{UploadsColumns[8]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "upload_project_id",
				Unique:  false,
				Columns: []*schema.Column{UploadsColumns[7]},
			},
			{
				Name:    "upload_user_id",
				Unique:  false,
				Columns: []*schema.Column{UploadsColumns[8]},
			},
			{
				Name:    "upload_camera_id",
				Unique:  false,
				Columns: []*schema.Column{UploadsColumns[6]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "createdAt", Type: field.TypeTime},
		{Name: "updatedAt", Type: field.TypeTime},
		{Name: "created_by", Type: field.TypeUUID, Nullable: true},
		{Name: "updated_by", Type: field.TypeUUID, Nullable: true},
		{Name: "legacy_id", Type: field.TypeString, Unique: true, Nullable: true},
		{Name: "username", Type: field.TypeString, Unique: true},
		{Name: "first_name", Type: field.TypeString},
		{Name: "last_name", Type: field.TypeString},
		{Name: "copyright_tag", Type: field.TypeString, Nullable: true},
		{Name: "active", Type: field.TypeBool, Default: false},
		{Name: "email", Type: field.TypeString, Unique: true, Nullable: true},
		{Name: "verified", Type: field.TypeBool, Default: false},
		{Name: "password_hash", Type: field.TypeString, Nullable: true},
		{Name: "force_password_change", Type: field.TypeBool, Default: false},
		{Name: "provider", Type: field.TypeEnum, Enums: []string{"local"}, Default: "local"},
		{Name: "role", Type: field.TypeEnum, Enums: []string{"user", "admin"}, Default: "user"},
		{Name: "active_project_id", Type: field.TypeString, Nullable: true, Size: 15},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "users_projects_activeProject",
				Columns:    []*schema.Column{UsersColumns[17]},
				RefColumns: []*schema.Column{ProjectsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "user_first_name_last_name",
				Unique:  true,
				Columns: []*schema.Column{UsersColumns[7], UsersColumns[8]},
			},
			{
				Name:    "user_active_project_id",
				Unique:  false,
				Columns: []*schema.Column{UsersColumns[17]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AuditLogsTable,
		CamerasTable,
		ImagesTable,
		ImageTagsTable,
		ImageTagAssignmentsTable,
		ProjectsTable,
		ProjectAssignmentsTable,
		RolesTable,
		TimeOffsetsTable,
		UploadsTable,
		UsersTable,
	}
)

func init() {
	CamerasTable.ForeignKeys[0].RefTable = UsersTable
	ImagesTable.ForeignKeys[0].RefTable = CamerasTable
	ImagesTable.ForeignKeys[1].RefTable = ProjectsTable
	ImagesTable.ForeignKeys[2].RefTable = UploadsTable
	ImagesTable.ForeignKeys[3].RefTable = UsersTable
	ImageTagsTable.ForeignKeys[0].RefTable = ProjectsTable
	ImageTagAssignmentsTable.ForeignKeys[0].RefTable = ImagesTable
	ImageTagAssignmentsTable.ForeignKeys[1].RefTable = ImageTagsTable
	ProjectAssignmentsTable.ForeignKeys[0].RefTable = ProjectsTable
	ProjectAssignmentsTable.ForeignKeys[1].RefTable = RolesTable
	ProjectAssignmentsTable.ForeignKeys[2].RefTable = UsersTable
	TimeOffsetsTable.ForeignKeys[0].RefTable = CamerasTable
	UploadsTable.ForeignKeys[0].RefTable = CamerasTable
	UploadsTable.ForeignKeys[1].RefTable = ProjectsTable
	UploadsTable.ForeignKeys[2].RefTable = UsersTable
	UsersTable.ForeignKeys[0].RefTable = ProjectsTable
}
