// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/shutterbase/shutterbase/ent/gallery"
	"github.com/shutterbase/shutterbase/ent/project"
	"github.com/shutterbase/shutterbase/ent/schema"
)

// GalleryCreate is the builder for creating a Gallery entity.
type GalleryCreate struct {
	config
	mutation *GalleryMutation
	hooks    []Hook
}

// SetCreatedAt sets the "createdAt" field.
func (_c *GalleryCreate) SetCreatedAt(v time.Time) *GalleryCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "createdAt" field if the given value is not nil.
func (_c *GalleryCreate) SetNillableCreatedAt(v *time.Time) *GalleryCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updatedAt" field.
func (_c *GalleryCreate) SetUpdatedAt(v time.Time) *GalleryCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updatedAt" field if the given value is not nil.
func (_c *GalleryCreate) SetNillableUpdatedAt(v *time.Time) *GalleryCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetCreatedBy sets the "createdBy" field.
func (_c *GalleryCreate) SetCreatedBy(v uuid.UUID) *GalleryCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "createdBy" field if the given value is not nil.
func (_c *GalleryCreate) SetNillableCreatedBy(v *uuid.UUID) *GalleryCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updatedBy" field.
func (_c *GalleryCreate) SetUpdatedBy(v uuid.UUID) *GalleryCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updatedBy" field if the given value is not nil.
func (_c *GalleryCreate) SetNillableUpdatedBy(v *uuid.UUID) *GalleryCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// SetKey sets the "key" field.
func (_c *GalleryCreate) SetKey(v string) *GalleryCreate {
	_c.mutation.SetKey(v)
	return _c
}

// SetName sets the "name" field.
func (_c *GalleryCreate) SetName(v string) *GalleryCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDomain sets the "domain" field.
func (_c *GalleryCreate) SetDomain(v string) *GalleryCreate {
	_c.mutation.SetDomain(v)
	return _c
}

// SetNillableDomain sets the "domain" field if the given value is not nil.
func (_c *GalleryCreate) SetNillableDomain(v *string) *GalleryCreate {
	if v != nil {
		_c.SetDomain(*v)
	}
	return _c
}

// SetTagline sets the "tagline" field.
func (_c *GalleryCreate) SetTagline(v string) *GalleryCreate {
	_c.mutation.SetTagline(v)
	return _c
}

// SetNillableTagline sets the "tagline" field if the given value is not nil.
func (_c *GalleryCreate) SetNillableTagline(v *string) *GalleryCreate {
	if v != nil {
		_c.SetTagline(*v)
	}
	return _c
}

// SetAboutText sets the "aboutText" field.
func (_c *GalleryCreate) SetAboutText(v string) *GalleryCreate {
	_c.mutation.SetAboutText(v)
	return _c
}

// SetNillableAboutText sets the "aboutText" field if the given value is not nil.
func (_c *GalleryCreate) SetNillableAboutText(v *string) *GalleryCreate {
	if v != nil {
		_c.SetAboutText(*v)
	}
	return _c
}

// SetFooterText sets the "footerText" field.
func (_c *GalleryCreate) SetFooterText(v string) *GalleryCreate {
	_c.mutation.SetFooterText(v)
	return _c
}

// SetNillableFooterText sets the "footerText" field if the given value is not nil.
func (_c *GalleryCreate) SetNillableFooterText(v *string) *GalleryCreate {
	if v != nil {
		_c.SetFooterText(*v)
	}
	return _c
}

// SetImprintUrl sets the "imprintUrl" field.
func (_c *GalleryCreate) SetImprintUrl(v string) *GalleryCreate {
	_c.mutation.SetImprintUrl(v)
	return _c
}

// SetNillableImprintUrl sets the "imprintUrl" field if the given value is not nil.
func (_c *GalleryCreate) SetNillableImprintUrl(v *string) *GalleryCreate {
	if v != nil {
		_c.SetImprintUrl(*v)
	}
	return _c
}

// SetPrivacyUrl sets the "privacyUrl" field.
func (_c *GalleryCreate) SetPrivacyUrl(v string) *GalleryCreate {
	_c.mutation.SetPrivacyUrl(v)
	return _c
}

// SetNillablePrivacyUrl sets the "privacyUrl" field if the given value is not nil.
func (_c *GalleryCreate) SetNillablePrivacyUrl(v *string) *GalleryCreate {
	if v != nil {
		_c.SetPrivacyUrl(*v)
	}
	return _c
}

// SetLocale sets the "locale" field.
func (_c *GalleryCreate) SetLocale(v gallery.Locale) *GalleryCreate {
	_c.mutation.SetLocale(v)
	return _c
}

// SetNillableLocale sets the "locale" field if the given value is not nil.
func (_c *GalleryCreate) SetNillableLocale(v *gallery.Locale) *GalleryCreate {
	if v != nil {
		_c.SetLocale(*v)
	}
	return _c
}

// SetLabels sets the "labels" field.
func (_c *GalleryCreate) SetLabels(v schema.GalleryLabels) *GalleryCreate {
	_c.mutation.SetLabels(v)
	return _c
}

// SetNillableLabels sets the "labels" field if the given value is not nil.
func (_c *GalleryCreate) SetNillableLabels(v *schema.GalleryLabels) *GalleryCreate {
	if v != nil {
		_c.SetLabels(*v)
	}
	return _c
}

// SetTheme sets the "theme" field.
func (_c *GalleryCreate) SetTheme(v schema.GalleryTheme) *GalleryCreate {
	_c.mutation.SetTheme(v)
	return _c
}

// SetNillableTheme sets the "theme" field if the given value is not nil.
func (_c *GalleryCreate) SetNillableTheme(v *schema.GalleryTheme) *GalleryCreate {
	if v != nil {
		_c.SetTheme(*v)
	}
	return _c
}

// SetSocialLinks sets the "socialLinks" field.
func (_c *GalleryCreate) SetSocialLinks(v []schema.SocialLink) *GalleryCreate {
	_c.mutation.SetSocialLinks(v)
	return _c
}

// SetLogoStorageId sets the "logoStorageId" field.
func (_c *GalleryCreate) SetLogoStorageId(v string) *GalleryCreate {
	_c.mutation.SetLogoStorageId(v)
	return _c
}

// SetNillableLogoStorageId sets the "logoStorageId" field if the given value is not nil.
func (_c *GalleryCreate) SetNillableLogoStorageId(v *string) *GalleryCreate {
	if v != nil {
		_c.SetLogoStorageId(*v)
	}
	return _c
}

// SetLogoDarkStorageId sets the "logoDarkStorageId" field.
func (_c *GalleryCreate) SetLogoDarkStorageId(v string) *GalleryCreate {
	_c.mutation.SetLogoDarkStorageId(v)
	return _c
}

// SetNillableLogoDarkStorageId sets the "logoDarkStorageId" field if the given value is not nil.
func (_c *GalleryCreate) SetNillableLogoDarkStorageId(v *string) *GalleryCreate {
	if v != nil {
		_c.SetLogoDarkStorageId(*v)
	}
	return _c
}

// SetFaviconStorageId sets the "faviconStorageId" field.
func (_c *GalleryCreate) SetFaviconStorageId(v string) *GalleryCreate {
	_c.mutation.SetFaviconStorageId(v)
	return _c
}

// SetNillableFaviconStorageId sets the "faviconStorageId" field if the given value is not nil.
func (_c *GalleryCreate) SetNillableFaviconStorageId(v *string) *GalleryCreate {
	if v != nil {
		_c.SetFaviconStorageId(*v)
	}
	return _c
}

// SetHeroStorageId sets the "heroStorageId" field.
func (_c *GalleryCreate) SetHeroStorageId(v string) *GalleryCreate {
	_c.mutation.SetHeroStorageId(v)
	return _c
}

// SetNillableHeroStorageId sets the "heroStorageId" field if the given value is not nil.
func (_c *GalleryCreate) SetNillableHeroStorageId(v *string) *GalleryCreate {
	if v != nil {
		_c.SetHeroStorageId(*v)
	}
	return _c
}

// SetBulkDownloadEnabled sets the "bulkDownloadEnabled" field.
func (_c *GalleryCreate) SetBulkDownloadEnabled(v bool) *GalleryCreate {
	_c.mutation.SetBulkDownloadEnabled(v)
	return _c
}

// SetNillableBulkDownloadEnabled sets the "bulkDownloadEnabled" field if the given value is not nil.
func (_c *GalleryCreate) SetNillableBulkDownloadEnabled(v *bool) *GalleryCreate {
	if v != nil {
		_c.SetBulkDownloadEnabled(*v)
	}
	return _c
}

// SetBulkDownloadMaxImages sets the "bulkDownloadMaxImages" field.
func (_c *GalleryCreate) SetBulkDownloadMaxImages(v int) *GalleryCreate {
	_c.mutation.SetBulkDownloadMaxImages(v)
	return _c
}

// SetNillableBulkDownloadMaxImages sets the "bulkDownloadMaxImages" field if the given value is not nil.
func (_c *GalleryCreate) SetNillableBulkDownloadMaxImages(v *int) *GalleryCreate {
	if v != nil {
		_c.SetBulkDownloadMaxImages(*v)
	}
	return _c
}

// SetActive sets the "active" field.
func (_c *GalleryCreate) SetActive(v bool) *GalleryCreate {
	_c.mutation.SetActive(v)
	return _c
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_c *GalleryCreate) SetNillableActive(v *bool) *GalleryCreate {
	if v != nil {
		_c.SetActive(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *GalleryCreate) SetID(v string) *GalleryCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *GalleryCreate) SetNillableID(v *string) *GalleryCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// AddProjectIDs adds the "projects" edge to the Project entity by IDs.
func (_c *GalleryCreate) AddProjectIDs(ids ...string) *GalleryCreate {
	_c.mutation.AddProjectIDs(ids...)
	return _c
}

// AddProjects adds the "projects" edges to the Project entity.
func (_c *GalleryCreate) AddProjects(v ...*Project) *GalleryCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddProjectIDs(ids...)
}

// Mutation returns the GalleryMutation object of the builder.
func (_c *GalleryCreate) Mutation() *GalleryMutation {
	return _c.mutation
}

// Save creates the Gallery in the database.
func (_c *GalleryCreate) Save(ctx context.Context) (*Gallery, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *GalleryCreate) SaveX(ctx context.Context) *Gallery {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GalleryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GalleryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *GalleryCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := gallery.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := gallery.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Locale(); !ok {
		v := gallery.DefaultLocale
		_c.mutation.SetLocale(v)
	}
	if _, ok := _c.mutation.SocialLinks(); !ok {
		v := gallery.DefaultSocialLinks
		_c.mutation.SetSocialLinks(v)
	}
	if _, ok := _c.mutation.BulkDownloadEnabled(); !ok {
		v := gallery.DefaultBulkDownloadEnabled
		_c.mutation.SetBulkDownloadEnabled(v)
	}
	if _, ok := _c.mutation.BulkDownloadMaxImages(); !ok {
		v := gallery.DefaultBulkDownloadMaxImages
		_c.mutation.SetBulkDownloadMaxImages(v)
	}
	if _, ok := _c.mutation.Active(); !ok {
		v := gallery.DefaultActive
		_c.mutation.SetActive(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := gallery.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *GalleryCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "createdAt", err: errors.New(`ent: missing required field "Gallery.createdAt"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updatedAt", err: errors.New(`ent: missing required field "Gallery.updatedAt"`)}
	}
	if _, ok := _c.mutation.Key(); !ok {
		return &ValidationError{Name: "key", err: errors.New(`ent: missing required field "Gallery.key"`)}
	}
	if v, ok := _c.mutation.Key(); ok {
		if err := gallery.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "Gallery.key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Gallery.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := gallery.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Gallery.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Locale(); !ok {
		return &ValidationError{Name: "locale", err: errors.New(`ent: missing required field "Gallery.locale"`)}
	}
	if v, ok := _c.mutation.Locale(); ok {
		if err := gallery.LocaleValidator(v); err != nil {
			return &ValidationError{Name: "locale", err: fmt.Errorf(`ent: validator failed for field "Gallery.locale": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BulkDownloadEnabled(); !ok {
		return &ValidationError{Name: "bulkDownloadEnabled", err: errors.New(`ent: missing required field "Gallery.bulkDownloadEnabled"`)}
	}
	if _, ok := _c.mutation.BulkDownloadMaxImages(); !ok {
		return &ValidationError{Name: "bulkDownloadMaxImages", err: errors.New(`ent: missing required field "Gallery.bulkDownloadMaxImages"`)}
	}
	if v, ok := _c.mutation.BulkDownloadMaxImages(); ok {
		if err := gallery.BulkDownloadMaxImagesValidator(v); err != nil {
			return &ValidationError{Name: "bulkDownloadMaxImages", err: fmt.Errorf(`ent: validator failed for field "Gallery.bulkDownloadMaxImages": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Active(); !ok {
		return &ValidationError{Name: "active", err: errors.New(`ent: missing required field "Gallery.active"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := gallery.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Gallery.id": %w`, err)}
		}
	}
	return nil
}

func (_c *GalleryCreate) sqlSave(ctx context.Context) (*Gallery, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Gallery.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *GalleryCreate) createSpec() (*Gallery, *sqlgraph.CreateSpec) {
	var (
		_node = &Gallery{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(gallery.Table, sqlgraph.NewFieldSpec(gallery.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(gallery.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(gallery.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(gallery.FieldCreatedBy, field.TypeUUID, value)
		_node.CreatedBy = &value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(gallery.FieldUpdatedBy, field.TypeUUID, value)
		_node.UpdatedBy = &value
	}
	if value, ok := _c.mutation.Key(); ok {
		_spec.SetField(gallery.FieldKey, field.TypeString, value)
		_node.Key = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(gallery.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Domain(); ok {
		_spec.SetField(gallery.FieldDomain, field.TypeString, value)
		_node.Domain = value
	}
	if value, ok := _c.mutation.Tagline(); ok {
		_spec.SetField(gallery.FieldTagline, field.TypeString, value)
		_node.Tagline = value
	}
	if value, ok := _c.mutation.AboutText(); ok {
		_spec.SetField(gallery.FieldAboutText, field.TypeString, value)
		_node.AboutText = value
	}
	if value, ok := _c.mutation.FooterText(); ok {
		_spec.SetField(gallery.FieldFooterText, field.TypeString, value)
		_node.FooterText = value
	}
	if value, ok := _c.mutation.ImprintUrl(); ok {
		_spec.SetField(gallery.FieldImprintUrl, field.TypeString, value)
		_node.ImprintUrl = value
	}
	if value, ok := _c.mutation.PrivacyUrl(); ok {
		_spec.SetField(gallery.FieldPrivacyUrl, field.TypeString, value)
		_node.PrivacyUrl = value
	}
	if value, ok := _c.mutation.Locale(); ok {
		_spec.SetField(gallery.FieldLocale, field.TypeEnum, value)
		_node.Locale = value
	}
	if value, ok := _c.mutation.Labels(); ok {
		_spec.SetField(gallery.FieldLabels, field.TypeJSON, value)
		_node.Labels = value
	}
	if value, ok := _c.mutation.Theme(); ok {
		_spec.SetField(gallery.FieldTheme, field.TypeJSON, value)
		_node.Theme = value
	}
	if value, ok := _c.mutation.SocialLinks(); ok {
		_spec.SetField(gallery.FieldSocialLinks, field.TypeJSON, value)
		_node.SocialLinks = value
	}
	if value, ok := _c.mutation.LogoStorageId(); ok {
		_spec.SetField(gallery.FieldLogoStorageId, field.TypeString, value)
		_node.LogoStorageId = value
	}
	if value, ok := _c.mutation.LogoDarkStorageId(); ok {
		_spec.SetField(gallery.FieldLogoDarkStorageId, field.TypeString, value)
		_node.LogoDarkStorageId = value
	}
	if value, ok := _c.mutation.FaviconStorageId(); ok {
		_spec.SetField(gallery.FieldFaviconStorageId, field.TypeString, value)
		_node.FaviconStorageId = value
	}
	if value, ok := _c.mutation.HeroStorageId(); ok {
		_spec.SetField(gallery.FieldHeroStorageId, field.TypeString, value)
		_node.HeroStorageId = value
	}
	if value, ok := _c.mutation.BulkDownloadEnabled(); ok {
		_spec.SetField(gallery.FieldBulkDownloadEnabled, field.TypeBool, value)
		_node.BulkDownloadEnabled = value
	}
	if value, ok := _c.mutation.BulkDownloadMaxImages(); ok {
		_spec.SetField(gallery.FieldBulkDownloadMaxImages, field.TypeInt, value)
		_node.BulkDownloadMaxImages = value
	}
	if value, ok := _c.mutation.Active(); ok {
		_spec.SetField(gallery.FieldActive, field.TypeBool, value)
		_node.Active = value
	}
	if nodes := _c.mutation.ProjectsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   gallery.ProjectsTable,
			Columns: []string{gallery.ProjectsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// GalleryCreateBulk is the builder for creating many Gallery entities in bulk.
type GalleryCreateBulk struct {
	config
	err      error
	builders []*GalleryCreate
}

// Save creates the Gallery entities in the database.
func (_c *GalleryCreateBulk) Save(ctx context.Context) ([]*Gallery, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Gallery, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GalleryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *GalleryCreateBulk) SaveX(ctx context.Context) []*Gallery {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GalleryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GalleryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
