// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/shutterbase/shutterbase/ent/image"
	"github.com/shutterbase/shutterbase/ent/imagetag"
	"github.com/shutterbase/shutterbase/ent/imagetagassignment"
)

// ImageTagAssignment is the model entity for the ImageTagAssignment schema.
type ImageTagAssignment struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id"`
	// CreatedAt holds the value of the "createdAt" field.
	CreatedAt time.Time `json:"createdAt"`
	// UpdatedAt holds the value of the "updatedAt" field.
	UpdatedAt time.Time `json:"updatedAt"`
	// CreatedBy holds the value of the "createdBy" field.
	CreatedBy *uuid.UUID `json:"createdBy,omitempty"`
	// UpdatedBy holds the value of the "updatedBy" field.
	UpdatedBy *uuid.UUID `json:"updatedBy,omitempty"`
	// Type holds the value of the "type" field.
	Type imagetagassignment.Type `json:"type"`
	// ImageID holds the value of the "image_id" field.
	ImageID string `json:"-"`
	// ImageTagID holds the value of the "image_tag_id" field.
	ImageTagID string `json:"-"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ImageTagAssignmentQuery when eager-loading is set.
	Edges        ImageTagAssignmentEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ImageTagAssignmentEdges holds the relations/edges for other nodes in the graph.
type ImageTagAssignmentEdges struct {
	// Image holds the value of the image edge.
	Image *Image `json:"image,omitempty"`
	// ImageTag holds the value of the imageTag edge.
	ImageTag *ImageTag `json:"imageTag,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ImageOrErr returns the Image value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ImageTagAssignmentEdges) ImageOrErr() (*Image, error) {
	if e.Image != nil {
		return e.Image, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: image.Label}
	}
	return nil, &NotLoadedError{edge: "image"}
}

// ImageTagOrErr returns the ImageTag value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ImageTagAssignmentEdges) ImageTagOrErr() (*ImageTag, error) {
	if e.ImageTag != nil {
		return e.ImageTag, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: imagetag.Label}
	}
	return nil, &NotLoadedError{edge: "imageTag"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ImageTagAssignment) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case imagetagassignment.FieldCreatedBy, imagetagassignment.FieldUpdatedBy:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case imagetagassignment.FieldID, imagetagassignment.FieldType, imagetagassignment.FieldImageID, imagetagassignment.FieldImageTagID:
			values[i] = new(sql.NullString)
		case imagetagassignment.FieldCreatedAt, imagetagassignment.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ImageTagAssignment fields.
func (_m *ImageTagAssignment) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case imagetagassignment.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case imagetagassignment.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field createdAt", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case imagetagassignment.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updatedAt", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case imagetagassignment.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field createdBy", values[i])
			} else if value.Valid {
				_m.CreatedBy = new(uuid.UUID)
				*_m.CreatedBy = *value.S.(*uuid.UUID)
			}
		case imagetagassignment.FieldUpdatedBy:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field updatedBy", values[i])
			} else if value.Valid {
				_m.UpdatedBy = new(uuid.UUID)
				*_m.UpdatedBy = *value.S.(*uuid.UUID)
			}
		case imagetagassignment.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = imagetagassignment.Type(value.String)
			}
		case imagetagassignment.FieldImageID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field image_id", values[i])
			} else if value.Valid {
				_m.ImageID = value.String
			}
		case imagetagassignment.FieldImageTagID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field image_tag_id", values[i])
			} else if value.Valid {
				_m.ImageTagID = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ImageTagAssignment.
// This includes values selected through modifiers, order, etc.
func (_m *ImageTagAssignment) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryImage queries the "image" edge of the ImageTagAssignment entity.
func (_m *ImageTagAssignment) QueryImage() *ImageQuery {
	return NewImageTagAssignmentClient(_m.config).QueryImage(_m)
}

// QueryImageTag queries the "imageTag" edge of the ImageTagAssignment entity.
func (_m *ImageTagAssignment) QueryImageTag() *ImageTagQuery {
	return NewImageTagAssignmentClient(_m.config).QueryImageTag(_m)
}

// Update returns a builder for updating this ImageTagAssignment.
// Note that you need to call ImageTagAssignment.Unwrap() before calling this method if this ImageTagAssignment
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ImageTagAssignment) Update() *ImageTagAssignmentUpdateOne {
	return NewImageTagAssignmentClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ImageTagAssignment entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ImageTagAssignment) Unwrap() *ImageTagAssignment {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ImageTagAssignment is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ImageTagAssignment) String() string {
	var builder strings.Builder
	builder.WriteString("ImageTagAssignment(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("createdAt=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updatedAt=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.CreatedBy; v != nil {
		builder.WriteString("createdBy=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.UpdatedBy; v != nil {
		builder.WriteString("updatedBy=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(fmt.Sprintf("%v", _m.Type))
	builder.WriteString(", ")
	builder.WriteString("image_id=")
	builder.WriteString(_m.ImageID)
	builder.WriteString(", ")
	builder.WriteString("image_tag_id=")
	builder.WriteString(_m.ImageTagID)
	builder.WriteByte(')')
	return builder.String()
}

// ImageTagAssignments is a parsable slice of ImageTagAssignment.
type ImageTagAssignments []*ImageTagAssignment
