// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/shutterbase/shutterbase/ent/batch"
	"github.com/shutterbase/shutterbase/ent/camera"
	"github.com/shutterbase/shutterbase/ent/image"
	"github.com/shutterbase/shutterbase/ent/imagetagassignment"
	"github.com/shutterbase/shutterbase/ent/project"
	"github.com/shutterbase/shutterbase/ent/user"
)

// ImageCreate is the builder for creating a Image entity.
type ImageCreate struct {
	config
	mutation *ImageMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (ic *ImageCreate) SetCreatedAt(t time.Time) *ImageCreate {
	ic.mutation.SetCreatedAt(t)
	return ic
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (ic *ImageCreate) SetNillableCreatedAt(t *time.Time) *ImageCreate {
	if t != nil {
		ic.SetCreatedAt(*t)
	}
	return ic
}

// SetUpdatedAt sets the "updated_at" field.
func (ic *ImageCreate) SetUpdatedAt(t time.Time) *ImageCreate {
	ic.mutation.SetUpdatedAt(t)
	return ic
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (ic *ImageCreate) SetNillableUpdatedAt(t *time.Time) *ImageCreate {
	if t != nil {
		ic.SetUpdatedAt(*t)
	}
	return ic
}

// SetThumbnailID sets the "thumbnail_id" field.
func (ic *ImageCreate) SetThumbnailID(u uuid.UUID) *ImageCreate {
	ic.mutation.SetThumbnailID(u)
	return ic
}

// SetNillableThumbnailID sets the "thumbnail_id" field if the given value is not nil.
func (ic *ImageCreate) SetNillableThumbnailID(u *uuid.UUID) *ImageCreate {
	if u != nil {
		ic.SetThumbnailID(*u)
	}
	return ic
}

// SetFileName sets the "file_name" field.
func (ic *ImageCreate) SetFileName(s string) *ImageCreate {
	ic.mutation.SetFileName(s)
	return ic
}

// SetComputedFileName sets the "computed_file_name" field.
func (ic *ImageCreate) SetComputedFileName(s string) *ImageCreate {
	ic.mutation.SetComputedFileName(s)
	return ic
}

// SetNillableComputedFileName sets the "computed_file_name" field if the given value is not nil.
func (ic *ImageCreate) SetNillableComputedFileName(s *string) *ImageCreate {
	if s != nil {
		ic.SetComputedFileName(*s)
	}
	return ic
}

// SetDescription sets the "description" field.
func (ic *ImageCreate) SetDescription(s string) *ImageCreate {
	ic.mutation.SetDescription(s)
	return ic
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (ic *ImageCreate) SetNillableDescription(s *string) *ImageCreate {
	if s != nil {
		ic.SetDescription(*s)
	}
	return ic
}

// SetExifData sets the "exif_data" field.
func (ic *ImageCreate) SetExifData(m map[string]interface{}) *ImageCreate {
	ic.mutation.SetExifData(m)
	return ic
}

// SetCapturedAt sets the "captured_at" field.
func (ic *ImageCreate) SetCapturedAt(t time.Time) *ImageCreate {
	ic.mutation.SetCapturedAt(t)
	return ic
}

// SetNillableCapturedAt sets the "captured_at" field if the given value is not nil.
func (ic *ImageCreate) SetNillableCapturedAt(t *time.Time) *ImageCreate {
	if t != nil {
		ic.SetCapturedAt(*t)
	}
	return ic
}

// SetCapturedAtCorrected sets the "captured_at_corrected" field.
func (ic *ImageCreate) SetCapturedAtCorrected(t time.Time) *ImageCreate {
	ic.mutation.SetCapturedAtCorrected(t)
	return ic
}

// SetNillableCapturedAtCorrected sets the "captured_at_corrected" field if the given value is not nil.
func (ic *ImageCreate) SetNillableCapturedAtCorrected(t *time.Time) *ImageCreate {
	if t != nil {
		ic.SetCapturedAtCorrected(*t)
	}
	return ic
}

// SetInferredAt sets the "inferred_at" field.
func (ic *ImageCreate) SetInferredAt(t time.Time) *ImageCreate {
	ic.mutation.SetInferredAt(t)
	return ic
}

// SetNillableInferredAt sets the "inferred_at" field if the given value is not nil.
func (ic *ImageCreate) SetNillableInferredAt(t *time.Time) *ImageCreate {
	if t != nil {
		ic.SetInferredAt(*t)
	}
	return ic
}

// SetID sets the "id" field.
func (ic *ImageCreate) SetID(u uuid.UUID) *ImageCreate {
	ic.mutation.SetID(u)
	return ic
}

// SetNillableID sets the "id" field if the given value is not nil.
func (ic *ImageCreate) SetNillableID(u *uuid.UUID) *ImageCreate {
	if u != nil {
		ic.SetID(*u)
	}
	return ic
}

// AddImageTagAssignmentIDs adds the "image_tag_assignments" edge to the ImageTagAssignment entity by IDs.
func (ic *ImageCreate) AddImageTagAssignmentIDs(ids ...uuid.UUID) *ImageCreate {
	ic.mutation.AddImageTagAssignmentIDs(ids...)
	return ic
}

// AddImageTagAssignments adds the "image_tag_assignments" edges to the ImageTagAssignment entity.
func (ic *ImageCreate) AddImageTagAssignments(i ...*ImageTagAssignment) *ImageCreate {
	ids := make([]uuid.UUID, len(i))
	for j := range i {
		ids[j] = i[j].ID
	}
	return ic.AddImageTagAssignmentIDs(ids...)
}

// SetUserID sets the "user" edge to the User entity by ID.
func (ic *ImageCreate) SetUserID(id uuid.UUID) *ImageCreate {
	ic.mutation.SetUserID(id)
	return ic
}

// SetUser sets the "user" edge to the User entity.
func (ic *ImageCreate) SetUser(u *User) *ImageCreate {
	return ic.SetUserID(u.ID)
}

// SetBatchID sets the "batch" edge to the Batch entity by ID.
func (ic *ImageCreate) SetBatchID(id uuid.UUID) *ImageCreate {
	ic.mutation.SetBatchID(id)
	return ic
}

// SetBatch sets the "batch" edge to the Batch entity.
func (ic *ImageCreate) SetBatch(b *Batch) *ImageCreate {
	return ic.SetBatchID(b.ID)
}

// SetProjectID sets the "project" edge to the Project entity by ID.
func (ic *ImageCreate) SetProjectID(id uuid.UUID) *ImageCreate {
	ic.mutation.SetProjectID(id)
	return ic
}

// SetProject sets the "project" edge to the Project entity.
func (ic *ImageCreate) SetProject(p *Project) *ImageCreate {
	return ic.SetProjectID(p.ID)
}

// SetCameraID sets the "camera" edge to the Camera entity by ID.
func (ic *ImageCreate) SetCameraID(id uuid.UUID) *ImageCreate {
	ic.mutation.SetCameraID(id)
	return ic
}

// SetCamera sets the "camera" edge to the Camera entity.
func (ic *ImageCreate) SetCamera(c *Camera) *ImageCreate {
	return ic.SetCameraID(c.ID)
}

// SetCreatedByID sets the "created_by" edge to the User entity by ID.
func (ic *ImageCreate) SetCreatedByID(id uuid.UUID) *ImageCreate {
	ic.mutation.SetCreatedByID(id)
	return ic
}

// SetNillableCreatedByID sets the "created_by" edge to the User entity by ID if the given value is not nil.
func (ic *ImageCreate) SetNillableCreatedByID(id *uuid.UUID) *ImageCreate {
	if id != nil {
		ic = ic.SetCreatedByID(*id)
	}
	return ic
}

// SetCreatedBy sets the "created_by" edge to the User entity.
func (ic *ImageCreate) SetCreatedBy(u *User) *ImageCreate {
	return ic.SetCreatedByID(u.ID)
}

// SetUpdatedByID sets the "updated_by" edge to the User entity by ID.
func (ic *ImageCreate) SetUpdatedByID(id uuid.UUID) *ImageCreate {
	ic.mutation.SetUpdatedByID(id)
	return ic
}

// SetNillableUpdatedByID sets the "updated_by" edge to the User entity by ID if the given value is not nil.
func (ic *ImageCreate) SetNillableUpdatedByID(id *uuid.UUID) *ImageCreate {
	if id != nil {
		ic = ic.SetUpdatedByID(*id)
	}
	return ic
}

// SetUpdatedBy sets the "updated_by" edge to the User entity.
func (ic *ImageCreate) SetUpdatedBy(u *User) *ImageCreate {
	return ic.SetUpdatedByID(u.ID)
}

// Mutation returns the ImageMutation object of the builder.
func (ic *ImageCreate) Mutation() *ImageMutation {
	return ic.mutation
}

// Save creates the Image in the database.
func (ic *ImageCreate) Save(ctx context.Context) (*Image, error) {
	ic.defaults()
	return withHooks(ctx, ic.sqlSave, ic.mutation, ic.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ic *ImageCreate) SaveX(ctx context.Context) *Image {
	v, err := ic.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ic *ImageCreate) Exec(ctx context.Context) error {
	_, err := ic.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ic *ImageCreate) ExecX(ctx context.Context) {
	if err := ic.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ic *ImageCreate) defaults() {
	if _, ok := ic.mutation.CreatedAt(); !ok {
		v := image.DefaultCreatedAt()
		ic.mutation.SetCreatedAt(v)
	}
	if _, ok := ic.mutation.UpdatedAt(); !ok {
		v := image.DefaultUpdatedAt()
		ic.mutation.SetUpdatedAt(v)
	}
	if _, ok := ic.mutation.ComputedFileName(); !ok {
		v := image.DefaultComputedFileName
		ic.mutation.SetComputedFileName(v)
	}
	if _, ok := ic.mutation.Description(); !ok {
		v := image.DefaultDescription
		ic.mutation.SetDescription(v)
	}
	if _, ok := ic.mutation.ExifData(); !ok {
		v := image.DefaultExifData
		ic.mutation.SetExifData(v)
	}
	if _, ok := ic.mutation.ID(); !ok {
		v := image.DefaultID()
		ic.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ic *ImageCreate) check() error {
	if _, ok := ic.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Image.created_at"`)}
	}
	if _, ok := ic.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Image.updated_at"`)}
	}
	if _, ok := ic.mutation.FileName(); !ok {
		return &ValidationError{Name: "file_name", err: errors.New(`ent: missing required field "Image.file_name"`)}
	}
	if v, ok := ic.mutation.FileName(); ok {
		if err := image.FileNameValidator(v); err != nil {
			return &ValidationError{Name: "file_name", err: fmt.Errorf(`ent: validator failed for field "Image.file_name": %w`, err)}
		}
	}
	if _, ok := ic.mutation.ComputedFileName(); !ok {
		return &ValidationError{Name: "computed_file_name", err: errors.New(`ent: missing required field "Image.computed_file_name"`)}
	}
	if _, ok := ic.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "Image.description"`)}
	}
	if _, ok := ic.mutation.ExifData(); !ok {
		return &ValidationError{Name: "exif_data", err: errors.New(`ent: missing required field "Image.exif_data"`)}
	}
	if _, ok := ic.mutation.UserID(); !ok {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "Image.user"`)}
	}
	if _, ok := ic.mutation.BatchID(); !ok {
		return &ValidationError{Name: "batch", err: errors.New(`ent: missing required edge "Image.batch"`)}
	}
	if _, ok := ic.mutation.ProjectID(); !ok {
		return &ValidationError{Name: "project", err: errors.New(`ent: missing required edge "Image.project"`)}
	}
	if _, ok := ic.mutation.CameraID(); !ok {
		return &ValidationError{Name: "camera", err: errors.New(`ent: missing required edge "Image.camera"`)}
	}
	return nil
}

func (ic *ImageCreate) sqlSave(ctx context.Context) (*Image, error) {
	if err := ic.check(); err != nil {
		return nil, err
	}
	_node, _spec := ic.createSpec()
	if err := sqlgraph.CreateNode(ctx, ic.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	ic.mutation.id = &_node.ID
	ic.mutation.done = true
	return _node, nil
}

func (ic *ImageCreate) createSpec() (*Image, *sqlgraph.CreateSpec) {
	var (
		_node = &Image{config: ic.config}
		_spec = sqlgraph.NewCreateSpec(image.Table, sqlgraph.NewFieldSpec(image.FieldID, field.TypeUUID))
	)
	if id, ok := ic.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := ic.mutation.CreatedAt(); ok {
		_spec.SetField(image.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := ic.mutation.UpdatedAt(); ok {
		_spec.SetField(image.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := ic.mutation.ThumbnailID(); ok {
		_spec.SetField(image.FieldThumbnailID, field.TypeUUID, value)
		_node.ThumbnailID = value
	}
	if value, ok := ic.mutation.FileName(); ok {
		_spec.SetField(image.FieldFileName, field.TypeString, value)
		_node.FileName = value
	}
	if value, ok := ic.mutation.ComputedFileName(); ok {
		_spec.SetField(image.FieldComputedFileName, field.TypeString, value)
		_node.ComputedFileName = value
	}
	if value, ok := ic.mutation.Description(); ok {
		_spec.SetField(image.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := ic.mutation.ExifData(); ok {
		_spec.SetField(image.FieldExifData, field.TypeJSON, value)
		_node.ExifData = value
	}
	if value, ok := ic.mutation.CapturedAt(); ok {
		_spec.SetField(image.FieldCapturedAt, field.TypeTime, value)
		_node.CapturedAt = value
	}
	if value, ok := ic.mutation.CapturedAtCorrected(); ok {
		_spec.SetField(image.FieldCapturedAtCorrected, field.TypeTime, value)
		_node.CapturedAtCorrected = value
	}
	if value, ok := ic.mutation.InferredAt(); ok {
		_spec.SetField(image.FieldInferredAt, field.TypeTime, value)
		_node.InferredAt = value
	}
	if nodes := ic.mutation.ImageTagAssignmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   image.ImageTagAssignmentsTable,
			Columns: []string{image.ImageTagAssignmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(imagetagassignment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := ic.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   image.UserTable,
			Columns: []string{image.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.image_user = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := ic.mutation.BatchIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   image.BatchTable,
			Columns: []string{image.BatchColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(batch.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.image_batch = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := ic.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   image.ProjectTable,
			Columns: []string{image.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.image_project = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := ic.mutation.CameraIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   image.CameraTable,
			Columns: []string{image.CameraColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(camera.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.image_camera = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := ic.mutation.CreatedByIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   image.CreatedByTable,
			Columns: []string{image.CreatedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.image_created_by = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := ic.mutation.UpdatedByIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   image.UpdatedByTable,
			Columns: []string{image.UpdatedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.image_updated_by = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ImageCreateBulk is the builder for creating many Image entities in bulk.
type ImageCreateBulk struct {
	config
	builders []*ImageCreate
}

// Save creates the Image entities in the database.
func (icb *ImageCreateBulk) Save(ctx context.Context) ([]*Image, error) {
	specs := make([]*sqlgraph.CreateSpec, len(icb.builders))
	nodes := make([]*Image, len(icb.builders))
	mutators := make([]Mutator, len(icb.builders))
	for i := range icb.builders {
		func(i int, root context.Context) {
			builder := icb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ImageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, icb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, icb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, icb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (icb *ImageCreateBulk) SaveX(ctx context.Context) []*Image {
	v, err := icb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (icb *ImageCreateBulk) Exec(ctx context.Context) error {
	_, err := icb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (icb *ImageCreateBulk) ExecX(ctx context.Context) {
	if err := icb.Exec(ctx); err != nil {
		panic(err)
	}
}
