// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/shutterbase/shutterbase/ent/personname"
	"github.com/shutterbase/shutterbase/ent/predicate"
)

// PersonNameUpdate is the builder for updating PersonName entities.
type PersonNameUpdate struct {
	config
	hooks    []Hook
	mutation *PersonNameMutation
}

// Where appends a list predicates to the PersonNameUpdate builder.
func (_u *PersonNameUpdate) Where(ps ...predicate.PersonName) *PersonNameUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updatedAt" field.
func (_u *PersonNameUpdate) SetUpdatedAt(v time.Time) *PersonNameUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUpdatedBy sets the "updatedBy" field.
func (_u *PersonNameUpdate) SetUpdatedBy(v uuid.UUID) *PersonNameUpdate {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updatedBy" field if the given value is not nil.
func (_u *PersonNameUpdate) SetNillableUpdatedBy(v *uuid.UUID) *PersonNameUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// ClearUpdatedBy clears the value of the "updatedBy" field.
func (_u *PersonNameUpdate) ClearUpdatedBy() *PersonNameUpdate {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetPersonRef sets the "personRef" field.
func (_u *PersonNameUpdate) SetPersonRef(v string) *PersonNameUpdate {
	_u.mutation.SetPersonRef(v)
	return _u
}

// SetNillablePersonRef sets the "personRef" field if the given value is not nil.
func (_u *PersonNameUpdate) SetNillablePersonRef(v *string) *PersonNameUpdate {
	if v != nil {
		_u.SetPersonRef(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *PersonNameUpdate) SetName(v string) *PersonNameUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *PersonNameUpdate) SetNillableName(v *string) *PersonNameUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// Mutation returns the PersonNameMutation object of the builder.
func (_u *PersonNameUpdate) Mutation() *PersonNameMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PersonNameUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PersonNameUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PersonNameUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PersonNameUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PersonNameUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := personname.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PersonNameUpdate) check() error {
	if v, ok := _u.mutation.PersonRef(); ok {
		if err := personname.PersonRefValidator(v); err != nil {
			return &ValidationError{Name: "personRef", err: fmt.Errorf(`ent: validator failed for field "PersonName.personRef": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := personname.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "PersonName.name": %w`, err)}
		}
	}
	return nil
}

func (_u *PersonNameUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(personname.Table, personname.Columns, sqlgraph.NewFieldSpec(personname.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(personname.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(personname.FieldCreatedBy, field.TypeUUID)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(personname.FieldUpdatedBy, field.TypeUUID, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(personname.FieldUpdatedBy, field.TypeUUID)
	}
	if value, ok := _u.mutation.PersonRef(); ok {
		_spec.SetField(personname.FieldPersonRef, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(personname.FieldName, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{personname.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PersonNameUpdateOne is the builder for updating a single PersonName entity.
type PersonNameUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PersonNameMutation
}

// SetUpdatedAt sets the "updatedAt" field.
func (_u *PersonNameUpdateOne) SetUpdatedAt(v time.Time) *PersonNameUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUpdatedBy sets the "updatedBy" field.
func (_u *PersonNameUpdateOne) SetUpdatedBy(v uuid.UUID) *PersonNameUpdateOne {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updatedBy" field if the given value is not nil.
func (_u *PersonNameUpdateOne) SetNillableUpdatedBy(v *uuid.UUID) *PersonNameUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// ClearUpdatedBy clears the value of the "updatedBy" field.
func (_u *PersonNameUpdateOne) ClearUpdatedBy() *PersonNameUpdateOne {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetPersonRef sets the "personRef" field.
func (_u *PersonNameUpdateOne) SetPersonRef(v string) *PersonNameUpdateOne {
	_u.mutation.SetPersonRef(v)
	return _u
}

// SetNillablePersonRef sets the "personRef" field if the given value is not nil.
func (_u *PersonNameUpdateOne) SetNillablePersonRef(v *string) *PersonNameUpdateOne {
	if v != nil {
		_u.SetPersonRef(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *PersonNameUpdateOne) SetName(v string) *PersonNameUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *PersonNameUpdateOne) SetNillableName(v *string) *PersonNameUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// Mutation returns the PersonNameMutation object of the builder.
func (_u *PersonNameUpdateOne) Mutation() *PersonNameMutation {
	return _u.mutation
}

// Where appends a list predicates to the PersonNameUpdate builder.
func (_u *PersonNameUpdateOne) Where(ps ...predicate.PersonName) *PersonNameUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PersonNameUpdateOne) Select(field string, fields ...string) *PersonNameUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PersonName entity.
func (_u *PersonNameUpdateOne) Save(ctx context.Context) (*PersonName, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PersonNameUpdateOne) SaveX(ctx context.Context) *PersonName {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PersonNameUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PersonNameUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PersonNameUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := personname.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PersonNameUpdateOne) check() error {
	if v, ok := _u.mutation.PersonRef(); ok {
		if err := personname.PersonRefValidator(v); err != nil {
			return &ValidationError{Name: "personRef", err: fmt.Errorf(`ent: validator failed for field "PersonName.personRef": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := personname.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "PersonName.name": %w`, err)}
		}
	}
	return nil
}

func (_u *PersonNameUpdateOne) sqlSave(ctx context.Context) (_node *PersonName, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(personname.Table, personname.Columns, sqlgraph.NewFieldSpec(personname.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PersonName.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, personname.FieldID)
		for _, f := range fields {
			if !personname.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != personname.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(personname.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(personname.FieldCreatedBy, field.TypeUUID)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(personname.FieldUpdatedBy, field.TypeUUID, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(personname.FieldUpdatedBy, field.TypeUUID)
	}
	if value, ok := _u.mutation.PersonRef(); ok {
		_spec.SetField(personname.FieldPersonRef, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(personname.FieldName, field.TypeString, value)
	}
	_node = &PersonName{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{personname.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
