// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/shutterbase/shutterbase/ent/personname"
)

// PersonNameCreate is the builder for creating a PersonName entity.
type PersonNameCreate struct {
	config
	mutation *PersonNameMutation
	hooks    []Hook
}

// SetCreatedAt sets the "createdAt" field.
func (_c *PersonNameCreate) SetCreatedAt(v time.Time) *PersonNameCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "createdAt" field if the given value is not nil.
func (_c *PersonNameCreate) SetNillableCreatedAt(v *time.Time) *PersonNameCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updatedAt" field.
func (_c *PersonNameCreate) SetUpdatedAt(v time.Time) *PersonNameCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updatedAt" field if the given value is not nil.
func (_c *PersonNameCreate) SetNillableUpdatedAt(v *time.Time) *PersonNameCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetCreatedBy sets the "createdBy" field.
func (_c *PersonNameCreate) SetCreatedBy(v uuid.UUID) *PersonNameCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "createdBy" field if the given value is not nil.
func (_c *PersonNameCreate) SetNillableCreatedBy(v *uuid.UUID) *PersonNameCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updatedBy" field.
func (_c *PersonNameCreate) SetUpdatedBy(v uuid.UUID) *PersonNameCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updatedBy" field if the given value is not nil.
func (_c *PersonNameCreate) SetNillableUpdatedBy(v *uuid.UUID) *PersonNameCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// SetPersonRef sets the "personRef" field.
func (_c *PersonNameCreate) SetPersonRef(v string) *PersonNameCreate {
	_c.mutation.SetPersonRef(v)
	return _c
}

// SetName sets the "name" field.
func (_c *PersonNameCreate) SetName(v string) *PersonNameCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetID sets the "id" field.
func (_c *PersonNameCreate) SetID(v string) *PersonNameCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *PersonNameCreate) SetNillableID(v *string) *PersonNameCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the PersonNameMutation object of the builder.
func (_c *PersonNameCreate) Mutation() *PersonNameMutation {
	return _c.mutation
}

// Save creates the PersonName in the database.
func (_c *PersonNameCreate) Save(ctx context.Context) (*PersonName, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PersonNameCreate) SaveX(ctx context.Context) *PersonName {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PersonNameCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PersonNameCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PersonNameCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := personname.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := personname.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := personname.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PersonNameCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "createdAt", err: errors.New(`ent: missing required field "PersonName.createdAt"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updatedAt", err: errors.New(`ent: missing required field "PersonName.updatedAt"`)}
	}
	if _, ok := _c.mutation.PersonRef(); !ok {
		return &ValidationError{Name: "personRef", err: errors.New(`ent: missing required field "PersonName.personRef"`)}
	}
	if v, ok := _c.mutation.PersonRef(); ok {
		if err := personname.PersonRefValidator(v); err != nil {
			return &ValidationError{Name: "personRef", err: fmt.Errorf(`ent: validator failed for field "PersonName.personRef": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "PersonName.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := personname.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "PersonName.name": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := personname.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "PersonName.id": %w`, err)}
		}
	}
	return nil
}

func (_c *PersonNameCreate) sqlSave(ctx context.Context) (*PersonName, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected PersonName.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PersonNameCreate) createSpec() (*PersonName, *sqlgraph.CreateSpec) {
	var (
		_node = &PersonName{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(personname.Table, sqlgraph.NewFieldSpec(personname.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(personname.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(personname.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(personname.FieldCreatedBy, field.TypeUUID, value)
		_node.CreatedBy = &value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(personname.FieldUpdatedBy, field.TypeUUID, value)
		_node.UpdatedBy = &value
	}
	if value, ok := _c.mutation.PersonRef(); ok {
		_spec.SetField(personname.FieldPersonRef, field.TypeString, value)
		_node.PersonRef = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(personname.FieldName, field.TypeString, value)
		_node.Name = value
	}
	return _node, _spec
}

// PersonNameCreateBulk is the builder for creating many PersonName entities in bulk.
type PersonNameCreateBulk struct {
	config
	err      error
	builders []*PersonNameCreate
}

// Save creates the PersonName entities in the database.
func (_c *PersonNameCreateBulk) Save(ctx context.Context) ([]*PersonName, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PersonName, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PersonNameMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PersonNameCreateBulk) SaveX(ctx context.Context) []*PersonName {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PersonNameCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PersonNameCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
