// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/shutterbase/shutterbase/ent/project"
)

// Project is the model entity for the Project schema.
type Project struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id"`
	// CreatedAt holds the value of the "createdAt" field.
	CreatedAt time.Time `json:"createdAt"`
	// UpdatedAt holds the value of the "updatedAt" field.
	UpdatedAt time.Time `json:"updatedAt"`
	// CreatedBy holds the value of the "createdBy" field.
	CreatedBy *uuid.UUID `json:"createdBy,omitempty"`
	// UpdatedBy holds the value of the "updatedBy" field.
	UpdatedBy *uuid.UUID `json:"updatedBy,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name"`
	// Description holds the value of the "description" field.
	Description string `json:"description"`
	// Copyright holds the value of the "copyright" field.
	Copyright string `json:"copyright"`
	// CopyrightReference holds the value of the "copyrightReference" field.
	CopyrightReference string `json:"copyrightReference"`
	// LocationName holds the value of the "locationName" field.
	LocationName string `json:"locationName"`
	// LocationCode holds the value of the "locationCode" field.
	LocationCode string `json:"locationCode"`
	// LocationCity holds the value of the "locationCity" field.
	LocationCity string `json:"locationCity"`
	// AiSystemMessage holds the value of the "aiSystemMessage" field.
	AiSystemMessage string `json:"aiSystemMessage"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ProjectQuery when eager-loading is set.
	Edges        ProjectEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ProjectEdges holds the relations/edges for other nodes in the graph.
type ProjectEdges struct {
	// Uploads holds the value of the uploads edge.
	Uploads []*Upload `json:"uploads,omitempty"`
	// Images holds the value of the images edge.
	Images []*Image `json:"images,omitempty"`
	// ImageTags holds the value of the imageTags edge.
	ImageTags []*ImageTag `json:"imageTags,omitempty"`
	// ProjectAssignments holds the value of the projectAssignments edge.
	ProjectAssignments []*ProjectAssignment `json:"projectAssignments,omitempty"`
	// ActiveForUsers holds the value of the activeForUsers edge.
	ActiveForUsers []*User `json:"activeForUsers,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [5]bool
}

// UploadsOrErr returns the Uploads value or an error if the edge
// was not loaded in eager-loading.
func (e ProjectEdges) UploadsOrErr() ([]*Upload, error) {
	if e.loadedTypes[0] {
		return e.Uploads, nil
	}
	return nil, &NotLoadedError{edge: "uploads"}
}

// ImagesOrErr returns the Images value or an error if the edge
// was not loaded in eager-loading.
func (e ProjectEdges) ImagesOrErr() ([]*Image, error) {
	if e.loadedTypes[1] {
		return e.Images, nil
	}
	return nil, &NotLoadedError{edge: "images"}
}

// ImageTagsOrErr returns the ImageTags value or an error if the edge
// was not loaded in eager-loading.
func (e ProjectEdges) ImageTagsOrErr() ([]*ImageTag, error) {
	if e.loadedTypes[2] {
		return e.ImageTags, nil
	}
	return nil, &NotLoadedError{edge: "imageTags"}
}

// ProjectAssignmentsOrErr returns the ProjectAssignments value or an error if the edge
// was not loaded in eager-loading.
func (e ProjectEdges) ProjectAssignmentsOrErr() ([]*ProjectAssignment, error) {
	if e.loadedTypes[3] {
		return e.ProjectAssignments, nil
	}
	return nil, &NotLoadedError{edge: "projectAssignments"}
}

// ActiveForUsersOrErr returns the ActiveForUsers value or an error if the edge
// was not loaded in eager-loading.
func (e ProjectEdges) ActiveForUsersOrErr() ([]*User, error) {
	if e.loadedTypes[4] {
		return e.ActiveForUsers, nil
	}
	return nil, &NotLoadedError{edge: "activeForUsers"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Project) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case project.FieldCreatedBy, project.FieldUpdatedBy:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case project.FieldID, project.FieldName, project.FieldDescription, project.FieldCopyright, project.FieldCopyrightReference, project.FieldLocationName, project.FieldLocationCode, project.FieldLocationCity, project.FieldAiSystemMessage:
			values[i] = new(sql.NullString)
		case project.FieldCreatedAt, project.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Project fields.
func (_m *Project) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case project.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case project.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field createdAt", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case project.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updatedAt", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case project.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field createdBy", values[i])
			} else if value.Valid {
				_m.CreatedBy = new(uuid.UUID)
				*_m.CreatedBy = *value.S.(*uuid.UUID)
			}
		case project.FieldUpdatedBy:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field updatedBy", values[i])
			} else if value.Valid {
				_m.UpdatedBy = new(uuid.UUID)
				*_m.UpdatedBy = *value.S.(*uuid.UUID)
			}
		case project.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case project.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case project.FieldCopyright:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field copyright", values[i])
			} else if value.Valid {
				_m.Copyright = value.String
			}
		case project.FieldCopyrightReference:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field copyrightReference", values[i])
			} else if value.Valid {
				_m.CopyrightReference = value.String
			}
		case project.FieldLocationName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field locationName", values[i])
			} else if value.Valid {
				_m.LocationName = value.String
			}
		case project.FieldLocationCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field locationCode", values[i])
			} else if value.Valid {
				_m.LocationCode = value.String
			}
		case project.FieldLocationCity:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field locationCity", values[i])
			} else if value.Valid {
				_m.LocationCity = value.String
			}
		case project.FieldAiSystemMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field aiSystemMessage", values[i])
			} else if value.Valid {
				_m.AiSystemMessage = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Project.
// This includes values selected through modifiers, order, etc.
func (_m *Project) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUploads queries the "uploads" edge of the Project entity.
func (_m *Project) QueryUploads() *UploadQuery {
	return NewProjectClient(_m.config).QueryUploads(_m)
}

// QueryImages queries the "images" edge of the Project entity.
func (_m *Project) QueryImages() *ImageQuery {
	return NewProjectClient(_m.config).QueryImages(_m)
}

// QueryImageTags queries the "imageTags" edge of the Project entity.
func (_m *Project) QueryImageTags() *ImageTagQuery {
	return NewProjectClient(_m.config).QueryImageTags(_m)
}

// QueryProjectAssignments queries the "projectAssignments" edge of the Project entity.
func (_m *Project) QueryProjectAssignments() *ProjectAssignmentQuery {
	return NewProjectClient(_m.config).QueryProjectAssignments(_m)
}

// QueryActiveForUsers queries the "activeForUsers" edge of the Project entity.
func (_m *Project) QueryActiveForUsers() *UserQuery {
	return NewProjectClient(_m.config).QueryActiveForUsers(_m)
}

// Update returns a builder for updating this Project.
// Note that you need to call Project.Unwrap() before calling this method if this Project
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Project) Update() *ProjectUpdateOne {
	return NewProjectClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Project entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Project) Unwrap() *Project {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Project is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Project) String() string {
	var builder strings.Builder
	builder.WriteString("Project(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("createdAt=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updatedAt=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.CreatedBy; v != nil {
		builder.WriteString("createdBy=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.UpdatedBy; v != nil {
		builder.WriteString("updatedBy=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("copyright=")
	builder.WriteString(_m.Copyright)
	builder.WriteString(", ")
	builder.WriteString("copyrightReference=")
	builder.WriteString(_m.CopyrightReference)
	builder.WriteString(", ")
	builder.WriteString("locationName=")
	builder.WriteString(_m.LocationName)
	builder.WriteString(", ")
	builder.WriteString("locationCode=")
	builder.WriteString(_m.LocationCode)
	builder.WriteString(", ")
	builder.WriteString("locationCity=")
	builder.WriteString(_m.LocationCity)
	builder.WriteString(", ")
	builder.WriteString("aiSystemMessage=")
	builder.WriteString(_m.AiSystemMessage)
	builder.WriteByte(')')
	return builder.String()
}

// Projects is a parsable slice of Project.
type Projects []*Project
