// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/shutterbase/shutterbase/ent/imagetag"
	"github.com/shutterbase/shutterbase/ent/project"
	"github.com/shutterbase/shutterbase/ent/scheduleitem"
	"github.com/shutterbase/shutterbase/ent/user"
)

// ScheduleItemCreate is the builder for creating a ScheduleItem entity.
type ScheduleItemCreate struct {
	config
	mutation *ScheduleItemMutation
	hooks    []Hook
}

// SetCreatedAt sets the "createdAt" field.
func (_c *ScheduleItemCreate) SetCreatedAt(v time.Time) *ScheduleItemCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "createdAt" field if the given value is not nil.
func (_c *ScheduleItemCreate) SetNillableCreatedAt(v *time.Time) *ScheduleItemCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updatedAt" field.
func (_c *ScheduleItemCreate) SetUpdatedAt(v time.Time) *ScheduleItemCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updatedAt" field if the given value is not nil.
func (_c *ScheduleItemCreate) SetNillableUpdatedAt(v *time.Time) *ScheduleItemCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetCreatedBy sets the "createdBy" field.
func (_c *ScheduleItemCreate) SetCreatedBy(v uuid.UUID) *ScheduleItemCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "createdBy" field if the given value is not nil.
func (_c *ScheduleItemCreate) SetNillableCreatedBy(v *uuid.UUID) *ScheduleItemCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updatedBy" field.
func (_c *ScheduleItemCreate) SetUpdatedBy(v uuid.UUID) *ScheduleItemCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updatedBy" field if the given value is not nil.
func (_c *ScheduleItemCreate) SetNillableUpdatedBy(v *uuid.UUID) *ScheduleItemCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// SetTitle sets the "title" field.
func (_c *ScheduleItemCreate) SetTitle(v string) *ScheduleItemCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *ScheduleItemCreate) SetDescription(v string) *ScheduleItemCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *ScheduleItemCreate) SetNillableDescription(v *string) *ScheduleItemCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetStart sets the "start" field.
func (_c *ScheduleItemCreate) SetStart(v time.Time) *ScheduleItemCreate {
	_c.mutation.SetStart(v)
	return _c
}

// SetEnd sets the "end" field.
func (_c *ScheduleItemCreate) SetEnd(v time.Time) *ScheduleItemCreate {
	_c.mutation.SetEnd(v)
	return _c
}

// SetCardinality sets the "cardinality" field.
func (_c *ScheduleItemCreate) SetCardinality(v int) *ScheduleItemCreate {
	_c.mutation.SetCardinality(v)
	return _c
}

// SetNillableCardinality sets the "cardinality" field if the given value is not nil.
func (_c *ScheduleItemCreate) SetNillableCardinality(v *int) *ScheduleItemCreate {
	if v != nil {
		_c.SetCardinality(*v)
	}
	return _c
}

// SetProjectID sets the "project_id" field.
func (_c *ScheduleItemCreate) SetProjectID(v string) *ScheduleItemCreate {
	_c.mutation.SetProjectID(v)
	return _c
}

// SetID sets the "id" field.
func (_c *ScheduleItemCreate) SetID(v string) *ScheduleItemCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ScheduleItemCreate) SetNillableID(v *string) *ScheduleItemCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetProject sets the "project" edge to the Project entity.
func (_c *ScheduleItemCreate) SetProject(v *Project) *ScheduleItemCreate {
	return _c.SetProjectID(v.ID)
}

// AddAssigneeIDs adds the "assignees" edge to the User entity by IDs.
func (_c *ScheduleItemCreate) AddAssigneeIDs(ids ...uuid.UUID) *ScheduleItemCreate {
	_c.mutation.AddAssigneeIDs(ids...)
	return _c
}

// AddAssignees adds the "assignees" edges to the User entity.
func (_c *ScheduleItemCreate) AddAssignees(v ...*User) *ScheduleItemCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAssigneeIDs(ids...)
}

// AddTagIDs adds the "tags" edge to the ImageTag entity by IDs.
func (_c *ScheduleItemCreate) AddTagIDs(ids ...string) *ScheduleItemCreate {
	_c.mutation.AddTagIDs(ids...)
	return _c
}

// AddTags adds the "tags" edges to the ImageTag entity.
func (_c *ScheduleItemCreate) AddTags(v ...*ImageTag) *ScheduleItemCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTagIDs(ids...)
}

// Mutation returns the ScheduleItemMutation object of the builder.
func (_c *ScheduleItemCreate) Mutation() *ScheduleItemMutation {
	return _c.mutation
}

// Save creates the ScheduleItem in the database.
func (_c *ScheduleItemCreate) Save(ctx context.Context) (*ScheduleItem, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ScheduleItemCreate) SaveX(ctx context.Context) *ScheduleItem {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ScheduleItemCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ScheduleItemCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ScheduleItemCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := scheduleitem.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := scheduleitem.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Cardinality(); !ok {
		v := scheduleitem.DefaultCardinality
		_c.mutation.SetCardinality(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := scheduleitem.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ScheduleItemCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "createdAt", err: errors.New(`ent: missing required field "ScheduleItem.createdAt"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updatedAt", err: errors.New(`ent: missing required field "ScheduleItem.updatedAt"`)}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "ScheduleItem.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := scheduleitem.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "ScheduleItem.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Start(); !ok {
		return &ValidationError{Name: "start", err: errors.New(`ent: missing required field "ScheduleItem.start"`)}
	}
	if _, ok := _c.mutation.End(); !ok {
		return &ValidationError{Name: "end", err: errors.New(`ent: missing required field "ScheduleItem.end"`)}
	}
	if _, ok := _c.mutation.Cardinality(); !ok {
		return &ValidationError{Name: "cardinality", err: errors.New(`ent: missing required field "ScheduleItem.cardinality"`)}
	}
	if v, ok := _c.mutation.Cardinality(); ok {
		if err := scheduleitem.CardinalityValidator(v); err != nil {
			return &ValidationError{Name: "cardinality", err: fmt.Errorf(`ent: validator failed for field "ScheduleItem.cardinality": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ProjectID(); !ok {
		return &ValidationError{Name: "project_id", err: errors.New(`ent: missing required field "ScheduleItem.project_id"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := scheduleitem.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "ScheduleItem.id": %w`, err)}
		}
	}
	if len(_c.mutation.ProjectIDs()) == 0 {
		return &ValidationError{Name: "project", err: errors.New(`ent: missing required edge "ScheduleItem.project"`)}
	}
	return nil
}

func (_c *ScheduleItemCreate) sqlSave(ctx context.Context) (*ScheduleItem, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected ScheduleItem.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ScheduleItemCreate) createSpec() (*ScheduleItem, *sqlgraph.CreateSpec) {
	var (
		_node = &ScheduleItem{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(scheduleitem.Table, sqlgraph.NewFieldSpec(scheduleitem.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(scheduleitem.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(scheduleitem.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(scheduleitem.FieldCreatedBy, field.TypeUUID, value)
		_node.CreatedBy = &value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(scheduleitem.FieldUpdatedBy, field.TypeUUID, value)
		_node.UpdatedBy = &value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(scheduleitem.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(scheduleitem.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Start(); ok {
		_spec.SetField(scheduleitem.FieldStart, field.TypeTime, value)
		_node.Start = value
	}
	if value, ok := _c.mutation.End(); ok {
		_spec.SetField(scheduleitem.FieldEnd, field.TypeTime, value)
		_node.End = value
	}
	if value, ok := _c.mutation.Cardinality(); ok {
		_spec.SetField(scheduleitem.FieldCardinality, field.TypeInt, value)
		_node.Cardinality = value
	}
	if nodes := _c.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   scheduleitem.ProjectTable,
			Columns: []string{scheduleitem.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ProjectID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AssigneesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   scheduleitem.AssigneesTable,
			Columns: scheduleitem.AssigneesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TagsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   scheduleitem.TagsTable,
			Columns: []string{scheduleitem.TagsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(imagetag.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ScheduleItemCreateBulk is the builder for creating many ScheduleItem entities in bulk.
type ScheduleItemCreateBulk struct {
	config
	err      error
	builders []*ScheduleItemCreate
}

// Save creates the ScheduleItem entities in the database.
func (_c *ScheduleItemCreateBulk) Save(ctx context.Context) ([]*ScheduleItem, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ScheduleItem, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ScheduleItemMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ScheduleItemCreateBulk) SaveX(ctx context.Context) []*ScheduleItem {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ScheduleItemCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ScheduleItemCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
