// Code generated by ent, DO NOT EDIT.

package image

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the image type in the database.
	Label = "image"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the createdat field in the database.
	FieldCreatedAt = "createdAt"
	// FieldUpdatedAt holds the string denoting the updatedat field in the database.
	FieldUpdatedAt = "updatedAt"
	// FieldCreatedBy holds the string denoting the createdby field in the database.
	FieldCreatedBy = "created_by"
	// FieldUpdatedBy holds the string denoting the updatedby field in the database.
	FieldUpdatedBy = "updated_by"
	// FieldFileName holds the string denoting the filename field in the database.
	FieldFileName = "file_name"
	// FieldComputedFileName holds the string denoting the computedfilename field in the database.
	FieldComputedFileName = "computed_file_name"
	// FieldStorageId holds the string denoting the storageid field in the database.
	FieldStorageId = "storage_id"
	// FieldExifData holds the string denoting the exifdata field in the database.
	FieldExifData = "exif_data"
	// FieldImageTags holds the string denoting the imagetags field in the database.
	FieldImageTags = "image_tags"
	// FieldCapturedAt holds the string denoting the capturedat field in the database.
	FieldCapturedAt = "captured_at"
	// FieldCapturedAtCorrected holds the string denoting the capturedatcorrected field in the database.
	FieldCapturedAtCorrected = "captured_at_corrected"
	// FieldInferredAt holds the string denoting the inferredat field in the database.
	FieldInferredAt = "inferred_at"
	// FieldSize holds the string denoting the size field in the database.
	FieldSize = "size"
	// FieldWidth holds the string denoting the width field in the database.
	FieldWidth = "width"
	// FieldHeight holds the string denoting the height field in the database.
	FieldHeight = "height"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldUploadID holds the string denoting the upload_id field in the database.
	FieldUploadID = "upload_id"
	// FieldProjectID holds the string denoting the project_id field in the database.
	FieldProjectID = "project_id"
	// FieldCameraID holds the string denoting the camera_id field in the database.
	FieldCameraID = "camera_id"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeUpload holds the string denoting the upload edge name in mutations.
	EdgeUpload = "upload"
	// EdgeProject holds the string denoting the project edge name in mutations.
	EdgeProject = "project"
	// EdgeCamera holds the string denoting the camera edge name in mutations.
	EdgeCamera = "camera"
	// EdgeImageTagAssignments holds the string denoting the imagetagassignments edge name in mutations.
	EdgeImageTagAssignments = "imageTagAssignments"
	// Table holds the table name of the image in the database.
	Table = "images"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "images"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
	// UploadTable is the table that holds the upload relation/edge.
	UploadTable = "images"
	// UploadInverseTable is the table name for the Upload entity.
	// It exists in this package in order to avoid circular dependency with the "upload" package.
	UploadInverseTable = "uploads"
	// UploadColumn is the table column denoting the upload relation/edge.
	UploadColumn = "upload_id"
	// ProjectTable is the table that holds the project relation/edge.
	ProjectTable = "images"
	// ProjectInverseTable is the table name for the Project entity.
	// It exists in this package in order to avoid circular dependency with the "project" package.
	ProjectInverseTable = "projects"
	// ProjectColumn is the table column denoting the project relation/edge.
	ProjectColumn = "project_id"
	// CameraTable is the table that holds the camera relation/edge.
	CameraTable = "images"
	// CameraInverseTable is the table name for the Camera entity.
	// It exists in this package in order to avoid circular dependency with the "camera" package.
	CameraInverseTable = "cameras"
	// CameraColumn is the table column denoting the camera relation/edge.
	CameraColumn = "camera_id"
	// ImageTagAssignmentsTable is the table that holds the imageTagAssignments relation/edge.
	ImageTagAssignmentsTable = "image_tag_assignments"
	// ImageTagAssignmentsInverseTable is the table name for the ImageTagAssignment entity.
	// It exists in this package in order to avoid circular dependency with the "imagetagassignment" package.
	ImageTagAssignmentsInverseTable = "image_tag_assignments"
	// ImageTagAssignmentsColumn is the table column denoting the imageTagAssignments relation/edge.
	ImageTagAssignmentsColumn = "image_id"
)

// Columns holds all SQL columns for image fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldCreatedBy,
	FieldUpdatedBy,
	FieldFileName,
	FieldComputedFileName,
	FieldStorageId,
	FieldExifData,
	FieldImageTags,
	FieldCapturedAt,
	FieldCapturedAtCorrected,
	FieldInferredAt,
	FieldSize,
	FieldWidth,
	FieldHeight,
	FieldUserID,
	FieldUploadID,
	FieldProjectID,
	FieldCameraID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "createdAt" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updatedAt" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updatedAt" field.
	UpdateDefaultUpdatedAt func() time.Time
	// FileNameValidator is a validator for the "fileName" field. It is called by the builders before save.
	FileNameValidator func(string) error
	// StorageIdValidator is a validator for the "storageId" field. It is called by the builders before save.
	StorageIdValidator func(string) error
	// DefaultImageTags holds the default value on creation for the "imageTags" field.
	DefaultImageTags []string
	// SizeValidator is a validator for the "size" field. It is called by the builders before save.
	SizeValidator func(int) error
	// WidthValidator is a validator for the "width" field. It is called by the builders before save.
	WidthValidator func(int) error
	// HeightValidator is a validator for the "height" field. It is called by the builders before save.
	HeightValidator func(int) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// OrderOption defines the ordering options for the Image queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the createdAt field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updatedAt field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByCreatedBy orders the results by the createdBy field.
func ByCreatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedBy, opts...).ToFunc()
}

// ByUpdatedBy orders the results by the updatedBy field.
func ByUpdatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedBy, opts...).ToFunc()
}

// ByFileName orders the results by the fileName field.
func ByFileName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFileName, opts...).ToFunc()
}

// ByComputedFileName orders the results by the computedFileName field.
func ByComputedFileName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldComputedFileName, opts...).ToFunc()
}

// ByStorageId orders the results by the storageId field.
func ByStorageId(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStorageId, opts...).ToFunc()
}

// ByCapturedAt orders the results by the capturedAt field.
func ByCapturedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCapturedAt, opts...).ToFunc()
}

// ByCapturedAtCorrected orders the results by the capturedAtCorrected field.
func ByCapturedAtCorrected(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCapturedAtCorrected, opts...).ToFunc()
}

// ByInferredAt orders the results by the inferredAt field.
func ByInferredAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInferredAt, opts...).ToFunc()
}

// BySize orders the results by the size field.
func BySize(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSize, opts...).ToFunc()
}

// ByWidth orders the results by the width field.
func ByWidth(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWidth, opts...).ToFunc()
}

// ByHeight orders the results by the height field.
func ByHeight(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHeight, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByUploadID orders the results by the upload_id field.
func ByUploadID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUploadID, opts...).ToFunc()
}

// ByProjectID orders the results by the project_id field.
func ByProjectID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProjectID, opts...).ToFunc()
}

// ByCameraID orders the results by the camera_id field.
func ByCameraID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCameraID, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByUploadField orders the results by upload field.
func ByUploadField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUploadStep(), sql.OrderByField(field, opts...))
	}
}

// ByProjectField orders the results by project field.
func ByProjectField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProjectStep(), sql.OrderByField(field, opts...))
	}
}

// ByCameraField orders the results by camera field.
func ByCameraField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCameraStep(), sql.OrderByField(field, opts...))
	}
}

// ByImageTagAssignmentsCount orders the results by imageTagAssignments count.
func ByImageTagAssignmentsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newImageTagAssignmentsStep(), opts...)
	}
}

// ByImageTagAssignments orders the results by imageTagAssignments terms.
func ByImageTagAssignments(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newImageTagAssignmentsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
func newUploadStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UploadInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UploadTable, UploadColumn),
	)
}
func newProjectStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProjectInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ProjectTable, ProjectColumn),
	)
}
func newCameraStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CameraInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, CameraTable, CameraColumn),
	)
}
func newImageTagAssignmentsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ImageTagAssignmentsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ImageTagAssignmentsTable, ImageTagAssignmentsColumn),
	)
}
