name: Build and Release

on:
  workflow_dispatch:

jobs:
  docker:
    name: Docker Build
    runs-on: ubuntu-latest
    permissions: write-all
    env:
      WASM_BUILDER_IMAGE: ghcr.io/shutterbase/wasm-builder
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build
        run: |
          docker pull $WASM_BUILDER_IMAGE:latest || true
          docker build --platform=linux/amd64 -t $WASM_BUILDER_IMAGE:latest --target wasm-builder .
          docker push $WASM_BUILDER_IMAGE:latest
